### ISSUE TITLE
Need to Setup "php presence bot" script to initiate at startup

### ISSUE THREAD

**Issue by mike7seven** [Denhac/presence-bot#3]
Need to Setup "php presence bot" script to initiate at startup, right now it has to be started manually. 

I modified the root crontab -e file by adding the line below.

@reboot cd  /home/pi/presence-bot/ && php presence bot

**Comment by Jnesselr** [comment]
I consider the crontab entry "good enough", unless you want to make this into a service.

**Comment by mike7seven** [comment]
This has been completed.
