### ISSUE TITLE
IRC Users

### ISSUE THREAD

**Issue by wcktklwn** [Denhac/presence-bot#8]
IRC users show up as "unknown"

**Comment by Jnesselr** [comment]
This is how the message events look: https://api.slack.com/events/message

Basically, either the presence bot is not getting a message for IRC users or the username is not listed in that message. I guess, technically, a 3rd option would be that the bridge itself gives 'unknown' as the username, but I doubt it.

**Comment by Jnesselr** [comment]
We're closing this as a 'won't fix'. Users can use the slack channel for registration and use IRC for all other communications.
